### ISSUE TITLE
Why directpython cannot import tensorflow?

### ISSUE THREAD

**Issue by zhaoxinyizhf** [anassinator/dqn-obstacle-avoidance#3]
Thanks a lot for your advice.
I have changed the version to Python 2.7 and tensorflow 1.6.0.
Still, Python can  import tensorflow but directpython cannot.
How can I fix it?

**Comment by anassinator** [comment]
Are you installing tensorflow globally (i.e. with `sudo`)?

**Comment by zhaoxinyizhf** [comment]
Thank you so much! It works now.

**Comment by anassinator** [comment]
No problem!
